version: 0.2

phases:
  pre_build:
    commands:
      - ansible-galaxy install -r roles/requirements.yml --force
  build:
    commands:
      - ansible-playbook site.yml -e env=development -e sts_disable=true -e cf_build_folder=build --tags generate

artifacts:
  files:
    - build/*