version: 0.2

phases:
  pre_build:
    commands:
      - make roles
  build:
    commands:
      - make generate/development /codebuild
      - make generate/production /codebuild

artifacts:
  files:
    - build/*